"""
IronBeam Python SDK

A comprehensive Python SDK for the IronBeam API with automated trade management.
"""

from .client import IronBeam
from .streaming import IronBeamStream, ConnectionState
from .trade_manager import (
    AutoBreakevenManager,
    RunningTPManager,
    AutoBreakevenConfig,
    RunningTPConfig,
    PositionState,
    BreakevenState
)
from .execution_engine import ThreadedExecutor, AsyncExecutor
from .models import (
    # Enums
    OrderSide,
    OrderType,
    DurationType,
    OrderStatus,
    PositionSide,
    BalanceType,
    # Authentication Models
    Token,
    AuthenticationRequest,
    LogoutResponse,
    # Account Models
    TraderInfo,
    UserInfo,
    Balance,
    AccountBalance,
    AccountBalanceRequest,
    Position,
    AccountPositions,
    Risk,
    AccountRisk,
    Fill,
    AccountFills,
    # Order Models
    OrderRequest,
    OrderUpdateRequest,
    Order,
    OrderResponse,
    OrdersRequest,
    OrdersResponse,
    OrdersFillsResponse,
    CancelOrderResponse,
    CancelMultipleRequest,
    CancelMultipleResponse,
    # Market Data Models
    Quote,
    QuotesRequest,
    QuotesResponse,
    Depth,
    DepthRequest,
    DepthResponse,
    Trade,
    TradesRequest,
    TradesResponse,
    # Security Models
    SecurityDefinition,
    SecurityDefinitionsRequest,
    SecurityDefinitionsResponse,
    SecurityMarginResponse,
    SecurityStatusResponse,
    # Symbol Search Models
    Symbol,
    SymbolsResponse,
    SymbolSearchRequest,
    ExchangeSource,
    ExchangeSourcesResponse,
    Complex,
    ComplexRequest,
    ComplexesResponse,
    FuturesSearchRequest,
    OptionsSearchRequest,
    StrategyIdRequest,
    StrategyIdResponse,
    OrderIdResponse,
    StrategyIdMappingResponse,
    # Streaming Models
    StreamResponse,
    SubscriptionRequest,
    SubscriptionResponse,
    UnsubscriptionResponse,
    IndicatorSubscriptionRequest,
    IndicatorSubscriptionResponse,
    IndicatorUnsubscriptionResponse,
    QuoteStreamMessage,
    DepthStreamMessage,
    TradeStreamMessage,
    OrderBookLevel,
    IndicatorBarData,
    IndicatorBarResponse,
    # Simulated Account Models
    SimulatedTraderRequest,
    SimulatedAccountRequest,
    SimulatedAccountResponse,
    SimulatedAccountCashRequest,
    SimulatedAccountCashResponse,
    SimulatedAccountResetResponse,
    SimulatedAccountExpireResponse,
    CashOperation,
    CashReportResponse,
    # Utility Models
    TradableAssetsResponse,
    TradableAssetsSummary,
    PopularSymbolsResponse,
    PopularSymbolCategory,
    KeywordSearchResponse,
    FuturesSearchResponse,
    OptionsSearchResponse,
    OptionGroupsResponse,
    OptionSpreadsResponse,
    CancelResult,
    SecurityMargin,
    SecurityStatus,
    DepthLevel
)
from .exceptions import (
    APIError, AuthenticationError, InvalidRequestError,
    RateLimitError, ServerError, ConnectionError, TimeoutError,
    StreamingError, OrderError, PositionError
)

__version__ = "0.1.0"

__all__ = [
    # Client
    "IronBeam",
    # Streaming
    "IronBeamStream",
    "ConnectionState",
    # Trade Management
    "AutoBreakevenManager",
    "RunningTPManager",
    "AutoBreakevenConfig",
    "RunningTPConfig",
    "PositionState",
    "BreakevenState",
    # Execution
    "ThreadedExecutor",
    "AsyncExecutor",
    # Enums
    "OrderSide",
    "OrderType",
    "DurationType",
    "OrderStatus",
    "PositionSide",
    "BalanceType",
    # Authentication Models
    "Token",
    "AuthenticationRequest",
    "LogoutResponse",
    # Account Models
    "TraderInfo",
    "UserInfo",
    "Balance",
    "AccountBalance",
    "AccountBalanceRequest",
    "Position",
    "AccountPositions",
    "Risk",
    "AccountRisk",
    "Fill",
    "AccountFills",
    # Order Models
    "OrderRequest",
    "OrderUpdateRequest",
    "Order",
    "OrderResponse",
    "OrdersRequest",
    "OrdersResponse",
    "OrdersFillsResponse",
    "CancelOrderResponse",
    "CancelMultipleRequest",
    "CancelMultipleResponse",
    "CancelResult",
    # Market Data Models
    "Quote",
    "QuotesRequest",
    "QuotesResponse",
    "Depth",
    "DepthRequest",
    "DepthResponse",
    "DepthLevel",
    "Trade",
    "TradesRequest",
    "TradesResponse",
    # Security Models
    "SecurityDefinition",
    "SecurityDefinitionsRequest",
    "SecurityDefinitionsResponse",
    "SecurityMargin",
    "SecurityMarginResponse",
    "SecurityStatus",
    "SecurityStatusResponse",
    # Symbol Search Models
    "Symbol",
    "SymbolsResponse",
    "SymbolSearchRequest",
    "ExchangeSource",
    "ExchangeSourcesResponse",
    "Complex",
    "ComplexRequest",
    "ComplexesResponse",
    "FuturesSearchRequest",
    "FuturesSearchResponse",
    "OptionsSearchRequest",
    "OptionsSearchResponse",
    "OptionGroupsResponse",
    "OptionSpreadsResponse",
    "StrategyIdRequest",
    "StrategyIdResponse",
    "OrderIdResponse",
    "StrategyIdMappingResponse",
    # Streaming Models
    "StreamResponse",
    "SubscriptionRequest",
    "SubscriptionResponse",
    "UnsubscriptionResponse",
    "IndicatorSubscriptionRequest",
    "IndicatorSubscriptionResponse",
    "IndicatorUnsubscriptionResponse",
    "QuoteStreamMessage",
    "DepthStreamMessage",
    "TradeStreamMessage",
    "OrderBookLevel",
    "IndicatorBarData",
    "IndicatorBarResponse",
    # Simulated Account Models
    "SimulatedTraderRequest",
    "SimulatedAccountRequest",
    "SimulatedAccountResponse",
    "SimulatedAccountCashRequest",
    "SimulatedAccountCashResponse",
    "SimulatedAccountResetResponse",
    "SimulatedAccountExpireResponse",
    "CashOperation",
    "CashReportResponse",
    # Utility Models
    "TradableAssetsResponse",
    "TradableAssetsSummary",
    "PopularSymbolsResponse",
    "PopularSymbolCategory",
    "KeywordSearchResponse",
    # Exceptions
    "APIError",
    "AuthenticationError",
    "InvalidRequestError",
    "RateLimitError",
    "ServerError",
    "ConnectionError", 
    "TimeoutError",
    "StreamingError",
    "OrderError",
    "PositionError",
]
